### ISSUE TITLE
PFD-C Coriolis reports wrong size when deflated

### ISSUE THREAD

**Issue by chris9871** [ChrisAdderley/StationPartsExpansionRedux#142] opened 2018-05-28 05:16 UTC
The size reported when deflated for Coriolis is 3.1m (correct) x 11.8m (probably incorrect) x 5.8m (probably correct).  Rotating it 45degrees results in 3.1m x 8.9m x 8.8m.

**Comment by chris9871** [comment] 2018-07-23 16:49
No, only this one.  I verified that all the other ones report values pretty close to expected.

**Comment by ChrisAdderley** [comment] 2018-08-08 21:01
Issue still under investigation - not sure what's wrong.

**Comment by ChrisAdderley** [comment] 2018-09-19 17:54
Think I got this :)

**Comment by chris9871** [comment] 2018-09-19 17:58
Cool beans!   I have, of course, long since launched my station, but I'll give it a try when it comes out!

**Comment by ChrisAdderley** [comment] 2018-09-21 20:08
Fixed in 1.0.6

**Closed by ChrisAdderley** 2018-09-21 20:08 UTC
Labels: bug, next version

**Comment by chris9871** [comment] 2018-09-22 03:03
Hmm, I just tried it in 1.0.6 and I notice two things in game.  1) it still seems to report the wonky 11.8m, and 2) it looks like there's flickering graphics issues as if two images were overlaid.

I wanted to make sure that I had the right version installed so I checked the GameData/StationPartsExpansionRedux and found that the version file says 1.0.5 even though ckan says 1.0.6 (so this could just be a ckan issue).

**Comment by ChrisAdderley** [comment] 2018-09-22 05:11
I found a small issue but did a deeper investigation. The real size of the part as calculated by the games does change now, but the Engineer's Report doesn't update unless you pick up and move the part (or the whole vessel or similar). This seems to occur with stock deploying parts like solar panels as well so I don't know if there's much I can do with it.

**Comment by chris9871** [comment] 2018-09-22 05:18
I noticed that as well and was taking that into account - move the object after shrinking it, then check the dimensions.

**Comment by chris9871** [comment] 2018-09-22 05:29
Ironically, the only reason I noticed it was when I tried to stick it into a Hangar (another mod).

**Comment by ChrisAdderley** [comment] 2018-09-22 05:31
Yeah I'm going to have to investigate how the game generates these. They appear to be related to drag cubes, but the cubes themselves are fine (after 1.0.6 at least) so I'm a little stumped.

**Comment by chris9871** [comment] 2018-09-22 07:03
I'm not 100% certain that I was using the right version - see above.  If it's a stumper, don't worry about it, the workaround are easy enough :)

**Comment by ChrisAdderley** [comment] 2018-09-22 19:03
Nah I repro'ed your problem in the dev branch so it must be for sure a problem.
My actual candidate for causing the problem is the deformable mesh of the tube. KSP doesn't calculate the bounds of these correctly some of the time so it might be running into that. 

I'll timebox maybe an hour more of time to investigation in the next day or two, but that's all I can commit to.
