### ISSUE TITLE
Centrifuges are disabling "Autostruts" on any preceding part (parent, grandparent)

### ISSUE THREAD

**Issue by bcqJC** [ChrisAdderley/StationPartsExpansionRedux#215] opened 2020-01-11 21:35 UTC
Environment: Win10 KSP 1.8.1 with all the DLCs; ModuleManage 4.1.3; SSPXR

Start a sandbox game.
In VAB, create a ship starting with Cupola.
Vertically stack a couple of SSPXR tubes starting from the bottom of the Cupola.
Attach a centrifuge at the bottom.
Attach another SSPXR tube at the bottom of the centrifuge.

Turn on "Visualize Autostruts" in the F12/Physics menu.
Set all parts to Autostrut:Grandparent. The autostruts should display on screen as 1 vertical line that extends from the bottom-most part.

Launch.

You'll see that only the bottom-most part has the Autostrut set. All other parts start from the centrifuge going up to the Cupola/Root will have Autostrut:Disabled.

Revert to VAB.

Remove the centrifuge from the ship. Launch. All Autostruts are set to Grandparent as initially set up above.

Logs attached.

[KSPLogs.zip](https://github.com/ChrisAdderley/StationPartsExpansionRedux/files/4049872/KSPLogs.zip)

**Comment by ChrisAdderley** [comment] 2020-01-12 01:37
Ok one important note: B9PartSwitch is critically required for the mod to work. I don't see that in your logs so that's a first red flag. It would be weird for it to cause this though.

I can't completely try the configuration you have because I lack the Breaking Ground DLC, so here's my test setup
- KSP 1.8.1
- Making History
- MM 4.1.3
- B9PS 2.12.1

Am I doing this right? I am not seeing what you are - Autostrut settings preserved on all parts when launching.
VAB:

![screenshot46](https://user-images.githubusercontent.com/5642064/72212812-be43a900-3498-11ea-8f0d-720cc50110b9.png)

Flight:
![screenshot45](https://user-images.githubusercontent.com/5642064/72212811-be43a900-3498-11ea-935a-54f0e4f8a766.png)

**Comment by ChrisAdderley** [comment] 2020-01-12 01:50
Ok ignore everything I just said. I think I finally managed to reproduce the problem, it's part of the code which tells the game to rebuild the IVA portraits. 

Going to need to research how to do this a different way I guess.

**Comment by ChrisAdderley** [comment] 2020-01-12 21:59
Fix released with 1.3.1.

**Closed** 2020-02-20 21:04 UTC
